import pg, { type QueryResult } from 'pg';
const connectionString =
	'postgresql://postgres:OQ39582ybUFHxKb6@db.knobgebkxacmiwrqqfec.supabase.co:5432/postgres';

export const pool = new pg.Pool({
	connectionString
});

type PostgresQueryResult = (sql: string, params?: any[]) => Promise<QueryResult<any>>;
export const query: PostgresQueryResult = (sql, params?) => pool.query(sql, params);

//pins schema
// create table
//   public.pins (
//     id bigint generated by default as identity,
//     created_at timestamp with time zone not null default now(),
//     latlng character varying null,
//     title character varying null,
//     description character varying null,
//     ip_address_creator character varying null,
//     type text not null,
//     constraint pins_pkey primary key (id)
//   ) tablespace pg_default;
